name: lists2
version: 1.0.0.0

dependencies:
  - base

library:
  exposed-modules: ListsPart2
  source-dirs: src
  ghc-options: -Wall -Wno-type-defaults

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - lists2
      - hspec
