name:                hello
version:             1.0.0.0
github:              "emiliolg/hello"
author:              "Emilio LG"

extra-source-files:
  - README.md

dependencies:
  - base

executables:
  hello:
    main:                Main.hs
    source-dirs:         app
    dependencies:
      - hello

library:
  exposed-modules: Hello
  source-dirs: src
  ghc-options: -Wall -Wno-type-defaults

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - hello
      - hspec

